CREATE TABLE IF NOT EXISTS notice (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event TEXT NOT NULL,
    created_at DATE DEFAULT CURRENT_DATE
);
CREATE TABLE IF NOT EXISTS history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event TEXT NOT NULL,
    created_at DATE DEFAULT CURRENT_DATE
);
